config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get "new/user", to: "user#new", as: :new_user
  post "new/user", to: "user#create", as: false
  delete "delete/user/:id", to: "user#destroy", as: :delete_user

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def new
		@user = User.new
	end

	def create
		user = User.create(user_params)

		if user.save
			redirect_to root_path
		else
			render :new
		end
	end

	def destroy
		user = User.find params[:id]
		user.delete

		respond_to do |format|
			format.html { redirect_to root_path }
		    format.json { head :no_content }
		    format.js   { render :layout => false }
		end
	end

	private
	def user_params
		params.require(:user).permit(:name)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@users = User.all.reverse
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ajax</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user/destroy.js.erb
$('.delete_user').bind('ajax:success', function() {  
        $(this).closest('tr').fadeOut();
});  

app/views/user/new.html.erb
<h1>New User</h1>

<%= form_for @user, url: new_user_path do |new_user| %>

	<%= new_user.label :name %>
	<%= new_user.text_field :name %>
	<br>
	<%= new_user.submit %>

<% end %>

app/views/welcome/index.html.erb
<h1>Hello World</h1>

<%= link_to "New User", new_user_path %>

<% @users.each do |user| %>
	<p><%= user.name %> <%= link_to "delete", delete_user_path(user.id), method: :delete, 
			data: {confirm: "Tem certeza?"}, remote: true, class: "delete_user" %></p>
<% end %>